baseURL = 'https://docko.dev'
languageCode = 'en-uk'
title = 'Docko Docs'
theme = 'hugo-book'
enableGitInfo = true

[params]
  BookTheme = 'dark'
  AuthorName = 'Karl Oberio'
  GitHubUser = 'doc-ko'
  BookRepo = 'https://github.com/doc-ko/doc-ko.github.io'

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|RUBYLIB|GEM_PATH|GO\w+)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.goTemplates]
    AllowActionJSTmpl = false

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
